### ISSUE TITLE
Inferring currency format

### ISSUE THREAD

**Issue by luileito** [foretagsplatsen/Numeral-js#11]
Hi, I just discovered this lib and I'm stuck at currency formatting:
```javascript
numeral.language("es", require("path/to/es.js"));
numeral.setLanguage("es");
var currency1 = numeral(100).format('$0,0.00'); // wrong: €100,00
var currency2 = numeral(100).formatCurrency('$0,0.00'); // wrong: €100,00
var currency3 = numeral(100).formatCurrency('0,0.00'); // right: 100,00 €
```
To me, the expected output in all cases is that of `currency3`. Is this a known bug?

Also, I'm wondering why is there an explicit `formatCurrency` method. I thought the `format` method would automatically infer there's a currency, a percentage, etc.

Thanks in advance, 
Luis

**Comment by BenjaminVanRyseghem** [comment]
- `currency1`: that's maybe a bug, or at least, something we forgot about :) This one should indeed output `100,00 €`
-`currency2`: here, you are forcing the currency symbol to be upfront, explaining why such an output :smile_cat: 

`formatCurrency` was introduced because ... we're a bit lazy :joy_cat: 
More seriously, since we mainly used this library at first to format currency, we decided to 

- not inject a `$` everywhere since our server is sending us raw numbers
- if a `$` is inserted, it will take precedence over the default settings

Hope you have a better understanding of this library now :smile:

**Comment by luileito** [comment]
Ok, thanks for your clarifications. So we should use only the `format` method (as soon as it becomes stable). Kudos for the lib!

**Comment by BenjaminVanRyseghem** [comment]
the way we use it now in our product is:

- `format` with '0[.]00 %' for percentage
- `format` with ',0[.]00' for numbers
- `formatCurrency` with default vales per language when currency

I think currency is a special case, since there is a lot of language specific formatting rules.
So the idea was to keep `formatCurrency` as a special case
